import { Product, SkateLevel, SkateDiscipline, ComponentType } from '@/types';

// Extend for mock purposes if needed, but we'll try to use the global one
export interface MockProduct extends Product {
  // Additional fields used only in configurator demo if any
  specs?: {
    label: string;
    value: number;
  }[];
  floorType?: 'liso' | 'rugoso' | 'mixto';
  badge?: string;
  badgeType?: 'new' | 'discount' | 'bestseller' | 'accent';
}

export const PRODUCTS: MockProduct[] = [
  {
    id: 'p3_10',
    name: 'Risport RF1 Elite',
    slug: 'risport-rf1-elite',
    brand_name: 'Risport',
    component_type: 'bota',
    skate_level: ['alto_rendimiento'],
    price_ars: 470000,
    description: 'Creado para los campeones del mañana. Construido con cuero natural de la más alta resistencia y termoformado anatómico ultra-preciso.',
    short_desc: 'Rigidez extrema y control absoluto para campeones mundiales.',
    images: [
      { id: 'img310_1', product_id: 'p3_10', url: 'https://i.ibb.co/84tmmn28/Risport-Venus.png', sort_order: 0, is_primary: true }
    ],
    is_featured: true,
    is_active: true,
    is_outlet: false,
    stock_quantity: 3,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre', 'saltos'],
    specs: [
      { label: 'Rigidez', value: 100 },
      { label: 'Control', value: 100 },
      { label: 'Desempeño', value: 99 },
    ],
  },
  {
    id: 'p3_5',
    name: 'Risport Dance Prime',
    slug: 'risport-dance-prime',
    brand_name: 'Risport',
    component_type: 'bota',
    skate_level: ['alto_rendimiento'],
    price_ars: 450000,
    description: 'La bota Dance Prime ha sido diseñada específicamente para las exigencias de la danza y solo danza. Excelente flexibilidad combinada con un perfil bajo y acolchado de espuma termoformable.',
    short_desc: 'El máximo estándar de excelencia para danza y precisión técnica.',
    images: [
      { id: 'img35_1', product_id: 'p3_5', url: 'https://i.ibb.co/84tmmn28/Risport-Venus.png', sort_order: 0, is_primary: true }
    ],
    is_featured: true,
    is_active: true,
    is_outlet: false,
    stock_quantity: 4,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['danza'],
    specs: [
      { label: 'Rigidez', value: 65 },
      { label: 'Peso', value: 85 },
      { label: 'Flexibilidad', value: 100 },
      { label: 'Acolchado', value: 95 },
      { label: 'Control', value: 98 },
    ],
  },
  {
    id: 'p3_6',
    name: 'Risport Ambra',
    slug: 'risport-ambra',
    brand_name: 'Risport',
    component_type: 'bota',
    skate_level: ['alto_rendimiento'],
    price_ars: 410000,
    description: 'Diseñada para patinadores profesionales que exigen un control absoluto en saltos y figuras.',
    short_desc: 'Soporte y rigidez premium para patinaje libre y figuras.',
    images: [
      { id: 'img36_1', product_id: 'p3_6', url: 'https://i.ibb.co/84tmmn28/Risport-Venus.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 5,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre', 'figuras'],
    specs: [
      { label: 'Rigidez', value: 90 },
      { label: 'Peso', value: 80 },
      { label: 'Acolchado', value: 85 },
    ],
  },
  {
    id: 'p3_4',
    name: 'Risport Royal Pro',
    slug: 'risport-royal-pro',
    brand_name: 'Risport',
    component_type: 'bota',
    skate_level: ['avanzado'],
    price_ars: 285000,
    description: 'Para patinadores de nivel avanzado que prefieren el tacto y la respuesta de las botas de cuero tradicionales combinadas con materiales modernos.',
    short_desc: 'El estándar de excelencia en botas de cuero profesionales.',
    images: [
      { id: 'img34_1', product_id: 'p3_4', url: 'https://i.ibb.co/84tmmn28/Risport-Venus.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 7,
    low_stock_threshold: 2,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre', 'danza'],
    specs: [
      { label: 'Rigidez', value: 75 },
      { label: 'Peso', value: 70 },
      { label: 'Acolchado', value: 98 },
      { label: 'Control', value: 92 },
      { label: 'Tradición', value: 100 },
    ],
  },
  {
    id: 'p3_8',
    name: 'Risport Antares',
    slug: 'risport-antares',
    brand_name: 'Risport',
    component_type: 'bota',
    skate_level: ['iniciacion', 'intermedio'],
    price_ars: 135000,
    description: 'Diseño liviano para patinadores que inician en competencias intermedias y saltos simples.',
    short_desc: 'Soporte y confort equilibrado para competidores en desarrollo.',
    images: [
      { id: 'img38_1', product_id: 'p3_8', url: 'https://i.ibb.co/84tmmn28/Risport-Venus.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 8,
    low_stock_threshold: 2,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre'],
    specs: [
      { label: 'Rigidez', value: 45 },
      { label: 'Peso', value: 85 },
      { label: 'Acolchado', value: 95 },
    ],
  },
  {
    id: 'p3_7',
    name: 'Risport Venus',
    slug: 'risport-venus',
    brand_name: 'Risport',
    component_type: 'bota',
    skate_level: ['iniciacion'],
    price_ars: 110000,
    description: 'La bota ideal para dar los primeros pasos en el patinaje artístico con comodidad y seguridad.',
    short_desc: 'Comodidad anatómica excelente para principiantes y escuelas.',
    images: [
      { id: 'img37_1', product_id: 'p3_7', url: 'https://i.ibb.co/84tmmn28/Risport-Venus.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 12,
    low_stock_threshold: 2,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre'],
    specs: [
      { label: 'Rigidez', value: 30 },
      { label: 'Peso', value: 90 },
      { label: 'Acolchado', value: 98 },
    ],
  },
  {
    id: 'p3_9',
    name: 'Risport Gemma',
    slug: 'risport-gemma',
    brand_name: 'Risport',
    component_type: 'bota',
    skate_level: ['iniciacion'],
    price_ars: 98000,
    description: 'Una bota muy confortable diseñada especialmente para los patinadores más jóvenes en sus fases iniciales de aprendizaje.',
    short_desc: 'Ideal para niños y principiantes. Suave acolchado y gran flexibilidad.',
    images: [
      { id: 'img39_1', product_id: 'p3_9', url: 'https://i.ibb.co/84tmmn28/Risport-Venus.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 15,
    low_stock_threshold: 3,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre'],
    specs: [
      { label: 'Rigidez', value: 20 },
      { label: 'Acolchado', value: 100 },
      { label: 'Confort', value: 100 },
    ],
  },
  {
    id: 'b1',
    name: 'Bolso Edea Always With Me',
    slug: 'bolso-edea-always-with-me',
    brand_name: 'Edea',
    component_type: 'accesorio',
    skate_level: ['iniciacion', 'intermedio', 'avanzado', 'alto_rendimiento'],
    price_ars: 75000,
    description: 'Bolso térmico de diseño italiano para llevar tus patines artísticos. Compartimento impermeable y bolsillos ventilados para proteger tu equipamiento técnico.',
    short_desc: 'Diseño elegante impermeable para transportar tus patines con comodidad.',
    images: [
      { id: 'img_b1', product_id: 'b1', url: 'https://i.ibb.co/8gcN7Lc1/Bolso-Edea-always-with-me.png', sort_order: 0, is_primary: true }
    ],
    is_featured: true,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10,
    low_stock_threshold: 2,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    badge: 'Popular',
    badgeType: 'bestseller',
  },
  {
    id: 'b2',
    name: 'Bolso Portapatines Magic Rosa',
    slug: 'bolso-magic-rosa',
    brand_name: 'Edea',
    component_type: 'accesorio',
    skate_level: ['iniciacion', 'intermedio'],
    price_ars: 45000,
    description: 'Bolso ultra liviano y resistente con bolsillos para herramientas y rodamientos.',
    short_desc: 'Bolso compacto y juvenil para tus entrenamientos diarios.',
    images: [
      { id: 'img_b2', product_id: 'b2', url: 'https://i.ibb.co/8gcN7Lc1/Bolso-Edea-always-with-me.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 15,
    low_stock_threshold: 3,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'b3',
    name: 'Bolso Portapatines Magic Celeste',
    slug: 'bolso-magic-celeste',
    brand_name: 'Edea',
    component_type: 'accesorio',
    skate_level: ['iniciacion', 'intermedio'],
    price_ars: 45000,
    description: 'Bolso ergonómico diseñado para la comodidad en el transporte diario.',
    short_desc: 'Espacioso y con ventilación lateral integrada.',
    images: [
      { id: 'img_b3', product_id: 'b3', url: 'https://i.ibb.co/8gcN7Lc1/Bolso-Edea-always-with-me.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 12,
    low_stock_threshold: 3,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p5',
    name: 'Roll-Line Giotto',
    slug: 'roll-line-giotto',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['alto_rendimiento'],
    price_ars: 155000,
    description: 'La plancha Giotto es la elección de los campeones mundiales de figuras. Su precisión milimétrica y su construcción en aleación de aluminio de grado aeronáutico la hacen insuperable.',
    short_desc: 'Precisión absoluta para la disciplina de figuras.',
    images: [
      { id: 'img5_1', product_id: 'p5', url: '', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 4,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['figuras'],
    specs: [
      { label: 'Estabilidad', value: 98 },
      { label: 'Agilidad', value: 70 },
      { label: 'Peso', value: 75 },
      { label: 'Respuesta', value: 95 },
      { label: 'Precisión', value: 100 },
    ],
  },
  {
    id: 'p5_2',
    name: 'Roll-Line Energy',
    slug: 'roll-line-energy',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['alto_rendimiento'],
    price_ars: 185000,
    description: 'La plancha de competición por excelencia. Agilidad extrema y respuesta instantánea.',
    short_desc: 'La elección de los profesionales para saltos y piruetas.',
    images: [
      { id: 'img52_1', product_id: 'p5_2', url: '', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 6,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre', 'saltos'],
    specs: [
      { label: 'Estabilidad', value: 85 },
      { label: 'Agilidad', value: 100 },
      { label: 'Peso', value: 95 },
      { label: 'Respuesta', value: 100 },
      { label: 'Precisión', value: 95 },
    ],
  },
  {
    id: 'pm1',
    name: 'Roll-Line Matrix',
    slug: 'roll-line-matrix',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['alto_rendimiento'],
    price_ars: 245000,
    description: 'La plancha de más alto nivel para patinadores profesionales. Estructura rebajada y geometría diferenciada.',
    short_desc: 'Estructura ultraliviana rebajada de máxima precisión.',
    images: [
      { id: 'img_pm1', product_id: 'pm1', url: '', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 3,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre', 'saltos'],
    specs: [
      { label: 'Estabilidad', value: 95 },
      { label: 'Agilidad', value: 98 },
      { label: 'Liviandad', value: 100 },
      { label: 'Respuesta', value: 98 },
    ],
  },
  {
    id: 'pm2',
    name: 'Roll-Line Evo',
    slug: 'roll-line-evo',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['alto_rendimiento'],
    price_ars: 225000,
    description: 'Una evolución tecnológica en el mundo de las planchas profesionales, con suspensiones de click micrométrico.',
    short_desc: 'Ajuste micrométrico y diseño de vanguardia.',
    images: [
      { id: 'img_pm2', product_id: 'pm2', url: '', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 4,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre'],
    specs: [
      { label: 'Estabilidad', value: 90 },
      { label: 'Agilidad', value: 95 },
      { label: 'Ajuste', value: 100 },
    ],
  },
  {
    id: 'pm3',
    name: 'Roll-Line Variant M',
    slug: 'roll-line-variant-m',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['intermedio'],
    price_ars: 98000,
    description: 'La plancha Variant M está diseñada para patinadores en ascenso. Excelente rigidez estructural de aluminio.',
    short_desc: 'Durabilidad y respuesta ágil de nivel intermedio.',
    images: [
      { id: 'img_pm3', product_id: 'pm3', url: '', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 8,
    low_stock_threshold: 2,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre'],
    specs: [
      { label: 'Estabilidad', value: 80 },
      { label: 'Agilidad', value: 75 },
      { label: 'Durabilidad', value: 95 },
    ],
  },
  {
    id: 'pm4',
    name: 'Roll-Line Mistral',
    slug: 'roll-line-mistral',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['avanzado'],
    price_ars: 135000,
    description: 'Plancha técnica de alta gama con tren de aluminio y suspensiones en elastómero de primera calidad.',
    short_desc: 'Chasis excelente para deportistas de alto nivel y saltos.',
    images: [
      { id: 'img_pm4', product_id: 'pm4', url: '', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 5,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre', 'saltos'],
    specs: [
      { label: 'Estabilidad', value: 85 },
      { label: 'Agilidad', value: 88 },
      { label: 'Control', value: 90 },
    ],
  },
  {
    id: 'pm5',
    name: 'Roll-Line Mariner Cup',
    slug: 'roll-line-mariner-cup',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['intermedio', 'avanzado'],
    price_ars: 110000,
    description: 'Perfectamente calibrada para figuras obligatorias y saltos intermedios. Excelente relación calidad/precio.',
    short_desc: 'Estabilidad superior y diseño clásico comprobado.',
    images: [
      { id: 'img_pm5', product_id: 'pm5', url: '', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 6,
    low_stock_threshold: 2,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['figuras'],
    specs: [
      { label: 'Estabilidad', value: 90 },
      { label: 'Control', value: 85 },
      { label: 'Precisión', value: 80 },
    ],
  },
  {
    id: 'pm6',
    name: 'Roll-Line Saturno',
    slug: 'roll-line-saturno',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['iniciacion'],
    price_ars: 72000,
    description: 'El chasis de iniciación ideal para academias y escuelas. Ligero, duradero y de fácil mantenimiento.',
    short_desc: 'Ligereza y confort para tus primeros giros.',
    images: [
      { id: 'img_pm6', product_id: 'pm6', url: '', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 12,
    low_stock_threshold: 3,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre'],
    specs: [
      { label: 'Flexibilidad', value: 90 },
      { label: 'Estabilidad', value: 85 },
      { label: 'Peso', value: 80 },
    ],
  },
  {
    id: 'pm7',
    name: 'Roll-Line Giotto Titanium',
    slug: 'roll-line-giotto-titanium',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['alto_rendimiento'],
    price_ars: 215000,
    description: 'Plancha ultra-especializada de figuras obligatorias con ejes de titanio para una ligereza inalcanzable.',
    short_desc: 'Edición limitada en titanio para la máxima precisión técnica.',
    images: [
      { id: 'img_pm7', product_id: 'pm7', url: '', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 3,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['figuras'],
    specs: [
      { label: 'Precisión', value: 100 },
      { label: 'Liviandad', value: 98 },
      { label: 'Control', value: 98 },
    ],
  },
  {
    id: 'pm8',
    name: 'Roll-Line Energy Steel',
    slug: 'roll-line-energy-steel',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['alto_rendimiento'],
    price_ars: 178000,
    description: 'La plancha más vendida para saltos triples y cuádruples, equipada con ejes de acero reforzado.',
    short_desc: 'Máxima durabilidad para los saltos más extremos.',
    images: [
      { id: 'img_pm8', product_id: 'pm8', url: '', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 5,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre', 'saltos'],
    specs: [
      { label: 'Resistencia', value: 100 },
      { label: 'Agilidad', value: 90 },
      { label: 'Control', value: 95 },
    ],
  },
  {
    id: 'pm9',
    name: 'Roll-Line Energy Titanium',
    slug: 'roll-line-energy-titanium',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['alto_rendimiento'],
    price_ars: 235000,
    description: 'La joya de la corona. Plancha Energy con ejes de titanio para saltar más alto y girar más rápido.',
    short_desc: 'La plancha definitiva de competición para saltos y piruetas.',
    images: [
      { id: 'img_pm9', product_id: 'pm9', url: '', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 2,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre', 'saltos'],
    specs: [
      { label: 'Liviandad', value: 100 },
      { label: 'Agilidad', value: 100 },
      { label: 'Amortiguación', value: 98 },
    ],
  },
  {
    id: 'pm10',
    name: 'Roll-Line Dance',
    slug: 'roll-line-dance',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['avanzado', 'alto_rendimiento'],
    price_ars: 165000,
    description: 'Geometría rebajada y trenes de ruedas optimizados para los movimientos fluidos y giros de solo danza.',
    short_desc: 'Diseñada específicamente para danza y precisión rítmica.',
    images: [
      { id: 'img_pm10', product_id: 'pm10', url: '', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 4,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['danza'],
    specs: [
      { label: 'Agilidad', value: 98 },
      { label: 'Flexibilidad', value: 95 },
      { label: 'Control', value: 95 },
    ],
  },
  {
    id: 'p6',
    name: 'Ruedas Komplex Angel',
    slug: 'komplex-angel',
    brand_name: 'Komplex',
    component_type: 'rueda',
    skate_level: ['avanzado'],
    price_ars: 45000,
    description: 'Ruedas profesionales con núcleo de elastómero que proporcionan un agarre excepcional en superficies resbaladizas sin comprometer la velocidad.',
    short_desc: 'Set de 8 ruedas profesionales de alta densidad.',
    images: [
      { id: 'img6_1', product_id: 'p6', url: '', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 20,
    low_stock_threshold: 4,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    badge: 'Nuevo',
    badgeType: 'new',
    skate_discipline: ['libre', 'danza'],
    floorType: 'liso',
    specs: [
      { label: 'Agarre', value: 85 },
      { label: 'Velocidad', value: 90 },
      { label: 'Deslize', value: 75 },
      { label: 'Durabilidad', value: 80 },
      { label: 'Rebote', value: 88 },
    ],
  },
  {
    id: 'p6_2',
    name: 'Ruedas Roll-Line Magnum',
    slug: 'roll-line-magnum',
    brand_name: 'Roll-Line',
    component_type: 'rueda',
    skate_level: ['intermedio'],
    price_ars: 40000,
    description: 'Perfectas para superficies rugosas and asfalto.',
    short_desc: 'Set de 8 ruedas para piso rugoso.',
    images: [
      { id: 'img62_1', product_id: 'p6_2', url: '', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 12,
    low_stock_threshold: 4,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    floorType: 'rugoso',
    skate_discipline: ['libre'],
    specs: [
      { label: 'Agarre', value: 95 },
      { label: 'Velocidad', value: 70 },
      { label: 'Deslize', value: 60 },
      { label: 'Durabilidad', value: 100 },
      { label: 'Amortiguación', value: 90 },
    ],
  },
  {
    id: 'p6_3',
    name: 'Ruedas Edea Fox',
    slug: 'edea-fox',
    brand_name: 'Edea',
    component_type: 'rueda',
    skate_level: ['avanzado'],
    price_ars: 42000,
    description: 'Equilibrio perfecto para quienes cambian de pista frecuentemente.',
    short_desc: 'Set de 8 ruedas mixtas.',
    images: [
      { id: 'img63_1', product_id: 'p6_3', url: 'https://i.ibb.co/8gcN7Lc1/Bolso-Edea-always-with-me.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 15,
    low_stock_threshold: 4,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    floorType: 'mixto',
    skate_discipline: ['libre', 'danza'],
    specs: [
      { label: 'Agarre', value: 80 },
      { label: 'Velocidad', value: 85 },
      { label: 'Deslize', value: 80 },
      { label: 'Durabilidad', value: 85 },
      { label: 'Versatilidad', value: 100 },
    ],
  },
  {
    id: 'p4',
    name: 'Combo Iniciación Profesional',
    slug: 'combo-iniciacion',
    brand_name: 'Sobre Ruedas',
    component_type: 'combo',
    skate_level: ['iniciacion'],
    price_ars: 135000,
    compare_price: 165000,
    description: 'Todo lo que necesitas para empezar con el pie derecho. Incluye bota de cuero reforzado, plancha de aluminio liviano y ruedas de dureza media aptas para todo tipo de superficies.',
    short_desc: 'Set completo: Bota + Plancha + Ruedas + Rodamientos.',
    images: [
      { id: 'img4_1', product_id: 'p4', url: '', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10,
    low_stock_threshold: 2,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    badge: '20% OFF',
    badgeType: 'discount',
    skate_discipline: ['libre'],
  },

  {
    id: 'new_prod_901',
    name: 'Roll Line Variant M',
    slug: 'roll-line-variant-m-901',
    brand_name: 'Roll Line',
    component_type: 'plancha',
    price_ars: 244538,
    description: 'Descripción para Roll Line Variant M. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_901_0', product_id: 'new_prod_901', url: 'https://i.ibb.co/20FQHH7J/Roll-Line-Variant-M-2.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_901_1', product_id: 'new_prod_901', url: 'https://i.ibb.co/k6kfzjSg/Roll-Line-Variant-M-1.png', sort_order: 1, is_primary: false },
      { id: 'img_new_prod_901_2', product_id: 'new_prod_901', url: 'https://i.ibb.co/95XjMJG/Roll-Line-Variant-M.png', sort_order: 2, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_902',
    name: 'Roll Line Variant f',
    slug: 'roll-line-variant-f-902',
    brand_name: 'Roll Line',
    component_type: 'plancha',
    price_ars: 138754,
    description: 'Descripción para Roll Line Variant f. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_902_0', product_id: 'new_prod_902', url: 'https://i.ibb.co/5hTWwVt2/Roll-Line-Variant-f-1.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_902_1', product_id: 'new_prod_902', url: 'https://i.ibb.co/1t9dF7fT/Roll-Line-Variant-f.png', sort_order: 1, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_903',
    name: 'Roll Line Variant C',
    slug: 'roll-line-variant-c-903',
    brand_name: 'Roll Line',
    component_type: 'plancha',
    price_ars: 169338,
    description: 'Descripción para Roll Line Variant C. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_903_0', product_id: 'new_prod_903', url: 'https://i.ibb.co/7xHB2Spv/Roll-Line-Variant-C-2.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_903_1', product_id: 'new_prod_903', url: 'https://i.ibb.co/9mcwRw0x/Roll-Line-Variant-C-1.png', sort_order: 1, is_primary: false },
      { id: 'img_new_prod_903_2', product_id: 'new_prod_903', url: 'https://i.ibb.co/mrg0h3s0/Roll-Line-Variant-C.png', sort_order: 2, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_904',
    name: 'Roll Line Spin',
    slug: 'roll-line-spin-904',
    brand_name: 'Roll Line',
    component_type: 'plancha',
    price_ars: 179822,
    description: 'Descripción para Roll Line Spin. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_904_0', product_id: 'new_prod_904', url: 'https://i.ibb.co/kVDNXT7Z/Roll-Line-Spin-2.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_904_1', product_id: 'new_prod_904', url: 'https://i.ibb.co/6RPrdvS5/Roll-Line-Spin-1.png', sort_order: 1, is_primary: false },
      { id: 'img_new_prod_904_2', product_id: 'new_prod_904', url: 'https://i.ibb.co/Y7qbvG2v/Roll-Line-Spin.png', sort_order: 2, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_905',
    name: 'Roll Line Saturno',
    slug: 'roll-line-saturno-905',
    brand_name: 'Roll Line',
    component_type: 'plancha',
    price_ars: 199775,
    description: 'Descripción para Roll Line Saturno. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_905_0', product_id: 'new_prod_905', url: 'https://i.ibb.co/Y4NBJpvL/Roll-Line-Saturno.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_905_1', product_id: 'new_prod_905', url: 'https://i.ibb.co/nq9g9Td7/Roll-Line-Saturno.png', sort_order: 1, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_906',
    name: 'Roll Line ruedas magnum',
    slug: 'roll-line-ruedas-magnum-906',
    brand_name: 'Roll Line',
    component_type: 'rueda',
    price_ars: 70309,
    description: 'Descripción para Roll Line ruedas magnum. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_906_0', product_id: 'new_prod_906', url: 'https://i.ibb.co/HMs8SvT/Roll-Line-ruedas-magnum-4.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_906_1', product_id: 'new_prod_906', url: 'https://i.ibb.co/qL6cCZXX/Roll-Line-ruedas-magnum-3.png', sort_order: 1, is_primary: false },
      { id: 'img_new_prod_906_2', product_id: 'new_prod_906', url: 'https://i.ibb.co/bjVtkfBr/Roll-Line-ruedas-magnum-2.png', sort_order: 2, is_primary: false },
      { id: 'img_new_prod_906_3', product_id: 'new_prod_906', url: 'https://i.ibb.co/B5Jvgkrp/Roll-Line-ruedas-magnum-1.png', sort_order: 3, is_primary: false },
      { id: 'img_new_prod_906_4', product_id: 'new_prod_906', url: 'https://i.ibb.co/jvMxyczh/Roll-Line-ruedas-magnum.png', sort_order: 4, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_907',
    name: 'Roll Line ruedas helium',
    slug: 'roll-line-ruedas-helium-907',
    brand_name: 'Roll Line',
    component_type: 'rueda',
    price_ars: 211042,
    description: 'Descripción para Roll Line ruedas helium. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_907_0', product_id: 'new_prod_907', url: 'https://i.ibb.co/1Jtv6ptc/Roll-Line-ruedas-helium-1.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_907_1', product_id: 'new_prod_907', url: 'https://i.ibb.co/SDTQ8ZBB/Roll-Line-ruedas-helium.png', sort_order: 1, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_908',
    name: 'Roll Line ruedas giotto',
    slug: 'roll-line-ruedas-giotto-908',
    brand_name: 'Roll Line',
    component_type: 'rueda',
    price_ars: 74183,
    description: 'Descripción para Roll Line ruedas giotto. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_908_0', product_id: 'new_prod_908', url: 'https://i.ibb.co/21cx1KRz/Roll-Line-ruedas-giotto-2.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_908_1', product_id: 'new_prod_908', url: 'https://i.ibb.co/MyV1qWJR/Roll-Line-ruedas-giotto-1.png', sort_order: 1, is_primary: false },
      { id: 'img_new_prod_908_2', product_id: 'new_prod_908', url: 'https://i.ibb.co/27x4zKRP/Roll-Line-ruedas-giotto.png', sort_order: 2, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_909',
    name: 'Roll Line ruedas boxer',
    slug: 'roll-line-ruedas-boxer-909',
    brand_name: 'Roll Line',
    component_type: 'rueda',
    price_ars: 60382,
    description: 'Descripción para Roll Line ruedas boxer. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_909_0', product_id: 'new_prod_909', url: 'https://i.ibb.co/tPhmhZQy/Roll-Line-ruedas-boxer-2.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_909_1', product_id: 'new_prod_909', url: 'https://i.ibb.co/twkfFR0L/Roll-Line-ruedas-boxer-1.png', sort_order: 1, is_primary: false },
      { id: 'img_new_prod_909_2', product_id: 'new_prod_909', url: 'https://i.ibb.co/7NSXMRkk/Roll-Line-ruedas-boxer.png', sort_order: 2, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_910',
    name: 'Roll Line Mistral',
    slug: 'roll-line-mistral-910',
    brand_name: 'Roll Line',
    component_type: 'plancha',
    price_ars: 142753,
    description: 'Descripción para Roll Line Mistral. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_910_0', product_id: 'new_prod_910', url: 'https://i.ibb.co/vCcLCJzm/Roll-Line-Mistral-2.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_911',
    name: 'Roll Line Mirage',
    slug: 'roll-line-mirage-911',
    brand_name: 'Roll Line',
    component_type: 'plancha',
    price_ars: 106384,
    description: 'Descripción para Roll Line Mirage. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_911_0', product_id: 'new_prod_911', url: 'https://i.ibb.co/LdKwnRPZ/Roll-Line-Mirage.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_911_1', product_id: 'new_prod_911', url: 'https://i.ibb.co/YBjYgtjb/Roll-Line-Mirage.png', sort_order: 1, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_912',
    name: 'Roll Line Matrix',
    slug: 'roll-line-matrix-912',
    brand_name: 'Roll Line',
    component_type: 'plancha',
    price_ars: 74985,
    description: 'Descripción para Roll Line Matrix. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_912_0', product_id: 'new_prod_912', url: 'https://i.ibb.co/JWZ7ZvF6/Roll-Line-Matrix.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_912_1', product_id: 'new_prod_912', url: 'https://i.ibb.co/7JyhBPwM/Roll-Line-Matrix-1.png', sort_order: 1, is_primary: false },
      { id: 'img_new_prod_912_2', product_id: 'new_prod_912', url: 'https://i.ibb.co/S4fM9kns/Roll-Line-Matrix.png', sort_order: 2, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_913',
    name: 'Roll Line giotto',
    slug: 'roll-line-giotto-913',
    brand_name: 'Roll Line',
    component_type: 'plancha',
    price_ars: 111011,
    description: 'Descripción para Roll Line giotto. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_913_0', product_id: 'new_prod_913', url: 'https://i.ibb.co/MkKdRKW4/Roll-Line-giotto-1.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_913_1', product_id: 'new_prod_913', url: 'https://i.ibb.co/wNm85s07/Roll-Line-giotto.png', sort_order: 1, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_914',
    name: 'Roll Line frenos rosas',
    slug: 'roll-line-frenos-rosas-914',
    brand_name: 'Roll Line',
    component_type: 'accesorio',
    price_ars: 189987,
    description: 'Descripción para Roll Line frenos rosas. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_914_0', product_id: 'new_prod_914', url: 'https://i.ibb.co/B515yXm1/Roll-Line-frenos-rosas.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_915',
    name: 'Roll Line frenos grises',
    slug: 'roll-line-frenos-grises-915',
    brand_name: 'Roll Line',
    component_type: 'accesorio',
    price_ars: 179575,
    description: 'Descripción para Roll Line frenos grises. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_915_0', product_id: 'new_prod_915', url: 'https://i.ibb.co/KjhD9tg0/Roll-Line-frenos-grises.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_916',
    name: 'Roll Line Evo',
    slug: 'roll-line-evo-916',
    brand_name: 'Roll Line',
    component_type: 'plancha',
    price_ars: 230402,
    description: 'Descripción para Roll Line Evo. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_916_0', product_id: 'new_prod_916', url: 'https://i.ibb.co/GQXrTqM5/Roll-Line-Evo-1.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_916_1', product_id: 'new_prod_916', url: 'https://i.ibb.co/YTw3VGP8/Roll-Line-Evo.png', sort_order: 1, is_primary: false },
      { id: 'img_new_prod_916_2', product_id: 'new_prod_916', url: 'https://i.ibb.co/8g4WfdjR/Roll-Line-Evo.png', sort_order: 2, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_917',
    name: 'Roll Line dance',
    slug: 'roll-line-dance-917',
    brand_name: 'Roll Line',
    component_type: 'plancha',
    price_ars: 245311,
    description: 'Descripción para Roll Line dance. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_917_0', product_id: 'new_prod_917', url: 'https://i.ibb.co/k6JJfjmn/Roll-Line-dance-2.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_917_1', product_id: 'new_prod_917', url: 'https://i.ibb.co/32Xp12P/Roll-Line-dance-1.png', sort_order: 1, is_primary: false },
      { id: 'img_new_prod_917_2', product_id: 'new_prod_917', url: 'https://i.ibb.co/KpQ2QW3f/Roll-Line-dance.png', sort_order: 2, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_918',
    name: 'Roll Line blaster',
    slug: 'roll-line-blaster-918',
    brand_name: 'Roll Line',
    component_type: 'plancha',
    price_ars: 132754,
    description: 'Descripción para Roll Line blaster. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_918_0', product_id: 'new_prod_918', url: 'https://i.ibb.co/PGVp2Q8C/Roll-Line-blaster-1.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_918_1', product_id: 'new_prod_918', url: 'https://i.ibb.co/pBDq0vdg/Roll-Line-blaster.png', sort_order: 1, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_919',
    name: 'Roll Line Avile',
    slug: 'roll-line-avile-919',
    brand_name: 'Roll Line',
    component_type: 'plancha',
    price_ars: 79872,
    description: 'Descripción para Roll Line Avile. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_919_0', product_id: 'new_prod_919', url: 'https://i.ibb.co/5xFRWWqw/Roll-Line-Avile.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_920',
    name: 'Roll Line agile',
    slug: 'roll-line-agile-920',
    brand_name: 'Roll Line',
    component_type: 'plancha',
    price_ars: 119719,
    description: 'Descripción para Roll Line agile. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_920_0', product_id: 'new_prod_920', url: 'https://i.ibb.co/Ld0FZxhC/Roll-Line-agile.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_920_1', product_id: 'new_prod_920', url: 'https://i.ibb.co/V07WxZt1/Roll-Line-agile.png', sort_order: 1, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_921',
    name: 'Risport Royal pro',
    slug: 'risport-royal-pro-921',
    brand_name: 'Risport',
    component_type: 'bota',
    price_ars: 233631,
    description: 'Descripción para Risport Royal pro. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_921_0', product_id: 'new_prod_921', url: 'https://i.ibb.co/Z4rXynv/Risport-Royal-pro.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_922',
    name: 'Risport RF1 elite',
    slug: 'risport-rf1-elite-922',
    brand_name: 'Risport',
    component_type: 'bota',
    price_ars: 241367,
    description: 'Descripción para Risport RF1 elite. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_922_0', product_id: 'new_prod_922', url: 'https://i.ibb.co/NQHrh87/Risport-RF1-elite-1.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_923',
    name: 'Risport gemma',
    slug: 'risport-gemma-923',
    brand_name: 'Risport',
    component_type: 'bota',
    price_ars: 192236,
    description: 'Descripción para Risport gemma. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_923_0', product_id: 'new_prod_923', url: 'https://i.ibb.co/4wh55MjV/Risport-gemma.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_924',
    name: 'Dance prime',
    slug: 'dance-prime-924',
    brand_name: 'Risport',
    component_type: 'bota',
    price_ars: 67232,
    description: 'Descripción para Dance prime. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_924_0', product_id: 'new_prod_924', url: 'https://i.ibb.co/d4VhV7bb/Dance-prime.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_925',
    name: 'Risport antares',
    slug: 'risport-antares-925',
    brand_name: 'Risport',
    component_type: 'bota',
    price_ars: 173634,
    description: 'Descripción para Risport antares. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_925_0', product_id: 'new_prod_925', url: 'https://i.ibb.co/WvtzdycW/Risport-antares.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'new_prod_926',
    name: 'Accesorio SR Patín',
    slug: 'accesorio-sr-pat-n-926',
    brand_name: 'Genérico',
    component_type: 'accesorio',
    price_ars: 79790,
    description: 'Descripción para Accesorio SR Patín. Producto de excelente calidad.',
    short_desc: 'Calidad superior y rendimiento óptimo.',
    images: [
      { id: 'img_new_prod_926_0', product_id: 'new_prod_926', url: 'https://i.ibb.co/v62XwXnT/Magic-Eraser-260526-160524.png', sort_order: 0, is_primary: true },
      { id: 'img_new_prod_926_1', product_id: 'new_prod_926', url: 'https://i.ibb.co/SwNbdXCN/Magic-Eraser-260526-160355.png', sort_order: 1, is_primary: false },
      { id: 'img_new_prod_926_2', product_id: 'new_prod_926', url: 'https://i.ibb.co/JRmtZBYd/Magic-Eraser-260526-155332.png', sort_order: 2, is_primary: false },
      { id: 'img_new_prod_926_3', product_id: 'new_prod_926', url: 'https://i.ibb.co/39rnGdV7/Magic-Eraser-260526-155309.png', sort_order: 3, is_primary: false },
      { id: 'img_new_prod_926_4', product_id: 'new_prod_926', url: 'https://i.ibb.co/JwjdLSJ7/Magic-Eraser-260526-155252.png', sort_order: 4, is_primary: false },
      { id: 'img_new_prod_926_5', product_id: 'new_prod_926', url: 'https://i.ibb.co/vxr81s5f/Magic-Eraser-260526-155236.png', sort_order: 5, is_primary: false },
      { id: 'img_new_prod_926_6', product_id: 'new_prod_926', url: 'https://i.ibb.co/C54Scqzr/Magic-Eraser-260526-155217.png', sort_order: 6, is_primary: false },
      { id: 'img_new_prod_926_7', product_id: 'new_prod_926', url: 'https://i.ibb.co/XZM3gCBV/Magic-Eraser-260526-155150.png', sort_order: 7, is_primary: false },
      { id: 'img_new_prod_926_8', product_id: 'new_prod_926', url: 'https://i.ibb.co/PsDnrQJn/Magic-Eraser-260526-151943.png', sort_order: 8, is_primary: false },
      { id: 'img_new_prod_926_9', product_id: 'new_prod_926', url: 'https://i.ibb.co/wFHxdLNN/Magic-Eraser-260526-151710.png', sort_order: 9, is_primary: false },
      { id: 'img_new_prod_926_10', product_id: 'new_prod_926', url: 'https://i.ibb.co/Hf0BJyQ5/Magic-Eraser-260526-151540.png', sort_order: 10, is_primary: false }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10, low_stock_threshold: 2, track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },


  {
    id: 'ice_1',
    name: 'Cuchilla John Wilson Pattern 99',
    slug: 'cuchilla-john-wilson-pattern-99',
    brand_name: 'John Wilson',
    component_type: 'cuchilla',
    skate_level: ['alto_rendimiento'],
    skate_type: 'hielo',
    price_ars: 550000,
    description: 'La cuchilla elegida por los campeones mundiales. Acero al carbono de la más alta calidad.',
    short_desc: 'Cuchilla de nivel elite para saltos triples y cuádruples.',
    images: [{ id: 'img_ice_1', product_id: 'ice_1', url: '', sort_order: 0, is_primary: true }], // placeholder
    is_active: true,
    is_featured: true,
    is_outlet: false,
    stock_quantity: 5,
    low_stock_threshold: 2,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'ice_2',
    name: 'Cuchilla MK Professional',
    slug: 'cuchilla-mk-professional',
    brand_name: 'MK',
    component_type: 'cuchilla',
    skate_level: ['intermedio', 'avanzado'],
    skate_type: 'hielo',
    price_ars: 280000,
    description: 'La cuchilla más popular para patinadores en desarrollo. Excelente balance y control.',
    short_desc: 'Cuchilla ideal para saltos simples y dobles.',
    images: [{ id: 'img_ice_2', product_id: 'ice_2', url: '', sort_order: 0, is_primary: true }], // placeholder
    is_active: true,
    is_featured: false,
    is_outlet: false,
    stock_quantity: 8,
    low_stock_threshold: 3,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'ice_3',
    name: 'Cuchilla Jackson Ultima Matrix',
    slug: 'cuchilla-jackson-ultima-matrix',
    brand_name: 'Jackson',
    component_type: 'cuchilla',
    skate_level: ['avanzado', 'alto_rendimiento'],
    skate_type: 'hielo',
    price_ars: 420000,
    description: 'Chasis de aluminio ligero con filo de acero inoxidable. 33% más liviana que las cuchillas tradicionales.',
    short_desc: 'Cuchilla ultraligera de rendimiento avanzado.',
    images: [{ id: 'img_ice_3', product_id: 'ice_3', url: '', sort_order: 0, is_primary: true }], // placeholder
    is_active: true,
    is_featured: false,
    is_outlet: false,
    stock_quantity: 4,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
];

export const BRANDS = ['Edea', 'Risport', 'Roll-Line', 'Komplex', 'Jackson', 'Sobre Ruedas', 'Sobre Ruedas Academy'];
export const CATEGORIES = [
  { id: 'bota', label: 'Botas' },
  { id: 'plancha', label: 'Planchas' },
  { id: 'rueda', label: 'Ruedas' },
  { id: 'accesorio', label: 'Bolsos y Accesorios' },
  { id: 'combo', label: 'Combos' },
  { id: 'curso', label: 'Cursos' },
  { id: 'cuchilla', label: 'Cuchillas' },
];
export const LEVELS = [
  { id: 'iniciacion', label: 'Iniciación' },
  { id: 'intermedio', label: 'Intermedio' },
  { id: 'avanzado', label: 'Avanzado' },
  { id: 'alto_rendimiento', label: 'Alto Rendimiento' },
];
