import { Product, SkateLevel, SkateDiscipline, ComponentType } from '@/types';

// Extend for mock purposes if needed, but we'll try to use the global one
export interface MockProduct extends Product {
  // Additional fields used only in configurator demo if any
  specs?: {
    label: string;
    value: number;
  }[];
  floorType?: 'liso' | 'rugoso' | 'mixto';
  badge?: string;
  badgeType?: 'new' | 'discount' | 'bestseller' | 'accent';
}

export const PRODUCTS: MockProduct[] = [
  {
    id: 'p3_10',
    name: 'Risport RF1 Elite',
    slug: 'risport-rf1-elite',
    brand_name: 'Risport',
    component_type: 'bota',
    skate_level: ['alto_rendimiento'],
    price_ars: 470000,
    description: 'Creado para los campeones del mañana. Construido con cuero natural de la más alta resistencia y termoformado anatómico ultra-preciso.',
    short_desc: 'Rigidez extrema y control absoluto para campeones mundiales.',
    images: [
      { id: 'img310_1', product_id: 'p3_10', url: 'https://i.ibb.co/84tmmn28/Risport-Venus.png', sort_order: 0, is_primary: true }
    ],
    is_featured: true,
    is_active: true,
    is_outlet: false,
    stock_quantity: 3,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre', 'saltos'],
    specs: [
      { label: 'Rigidez', value: 100 },
      { label: 'Control', value: 100 },
      { label: 'Desempeño', value: 99 },
    ],
  },
  {
    id: 'p3_5',
    name: 'Risport Dance Prime',
    slug: 'risport-dance-prime',
    brand_name: 'Risport',
    component_type: 'bota',
    skate_level: ['alto_rendimiento'],
    price_ars: 450000,
    description: 'La bota Dance Prime ha sido diseñada específicamente para las exigencias de la danza y solo danza. Excelente flexibilidad combinada con un perfil bajo y acolchado de espuma termoformable.',
    short_desc: 'El máximo estándar de excelencia para danza y precisión técnica.',
    images: [
      { id: 'img35_1', product_id: 'p3_5', url: 'https://i.ibb.co/84tmmn28/Risport-Venus.png', sort_order: 0, is_primary: true }
    ],
    is_featured: true,
    is_active: true,
    is_outlet: false,
    stock_quantity: 4,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['danza'],
    specs: [
      { label: 'Rigidez', value: 65 },
      { label: 'Peso', value: 85 },
      { label: 'Flexibilidad', value: 100 },
      { label: 'Acolchado', value: 95 },
      { label: 'Control', value: 98 },
    ],
  },
  {
    id: 'p3_6',
    name: 'Risport Ambra',
    slug: 'risport-ambra',
    brand_name: 'Risport',
    component_type: 'bota',
    skate_level: ['alto_rendimiento'],
    price_ars: 410000,
    description: 'Diseñada para patinadores profesionales que exigen un control absoluto en saltos y figuras.',
    short_desc: 'Soporte y rigidez premium para patinaje libre y figuras.',
    images: [
      { id: 'img36_1', product_id: 'p3_6', url: 'https://i.ibb.co/84tmmn28/Risport-Venus.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 5,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre', 'figuras'],
    specs: [
      { label: 'Rigidez', value: 90 },
      { label: 'Peso', value: 80 },
      { label: 'Acolchado', value: 85 },
    ],
  },
  {
    id: 'p3_4',
    name: 'Risport Royal Pro',
    slug: 'risport-royal-pro',
    brand_name: 'Risport',
    component_type: 'bota',
    skate_level: ['avanzado'],
    price_ars: 285000,
    description: 'Para patinadores de nivel avanzado que prefieren el tacto y la respuesta de las botas de cuero tradicionales combinadas con materiales modernos.',
    short_desc: 'El estándar de excelencia en botas de cuero profesionales.',
    images: [
      { id: 'img34_1', product_id: 'p3_4', url: 'https://i.ibb.co/84tmmn28/Risport-Venus.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 7,
    low_stock_threshold: 2,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre', 'danza'],
    specs: [
      { label: 'Rigidez', value: 75 },
      { label: 'Peso', value: 70 },
      { label: 'Acolchado', value: 98 },
      { label: 'Control', value: 92 },
      { label: 'Tradición', value: 100 },
    ],
  },
  {
    id: 'p3_8',
    name: 'Risport Antares',
    slug: 'risport-antares',
    brand_name: 'Risport',
    component_type: 'bota',
    skate_level: ['iniciacion', 'intermedio'],
    price_ars: 135000,
    description: 'Diseño liviano para patinadores que inician en competencias intermedias y saltos simples.',
    short_desc: 'Soporte y confort equilibrado para competidores en desarrollo.',
    images: [
      { id: 'img38_1', product_id: 'p3_8', url: 'https://i.ibb.co/84tmmn28/Risport-Venus.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 8,
    low_stock_threshold: 2,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre'],
    specs: [
      { label: 'Rigidez', value: 45 },
      { label: 'Peso', value: 85 },
      { label: 'Acolchado', value: 95 },
    ],
  },
  {
    id: 'p3_7',
    name: 'Risport Venus',
    slug: 'risport-venus',
    brand_name: 'Risport',
    component_type: 'bota',
    skate_level: ['iniciacion'],
    price_ars: 110000,
    description: 'La bota ideal para dar los primeros pasos en el patinaje artístico con comodidad y seguridad.',
    short_desc: 'Comodidad anatómica excelente para principiantes y escuelas.',
    images: [
      { id: 'img37_1', product_id: 'p3_7', url: 'https://i.ibb.co/84tmmn28/Risport-Venus.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 12,
    low_stock_threshold: 2,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre'],
    specs: [
      { label: 'Rigidez', value: 30 },
      { label: 'Peso', value: 90 },
      { label: 'Acolchado', value: 98 },
    ],
  },
  {
    id: 'p3_9',
    name: 'Risport Gemma',
    slug: 'risport-gemma',
    brand_name: 'Risport',
    component_type: 'bota',
    skate_level: ['iniciacion'],
    price_ars: 98000,
    description: 'Una bota muy confortable diseñada especialmente para los patinadores más jóvenes en sus fases iniciales de aprendizaje.',
    short_desc: 'Ideal para niños y principiantes. Suave acolchado y gran flexibilidad.',
    images: [
      { id: 'img39_1', product_id: 'p3_9', url: 'https://i.ibb.co/84tmmn28/Risport-Venus.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 15,
    low_stock_threshold: 3,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre'],
    specs: [
      { label: 'Rigidez', value: 20 },
      { label: 'Acolchado', value: 100 },
      { label: 'Confort', value: 100 },
    ],
  },
  {
    id: 'b1',
    name: 'Bolso Edea Always With Me',
    slug: 'bolso-edea-always-with-me',
    brand_name: 'Edea',
    component_type: 'accesorio',
    skate_level: ['iniciacion', 'intermedio', 'avanzado', 'alto_rendimiento'],
    price_ars: 75000,
    description: 'Bolso térmico de diseño italiano para llevar tus patines artísticos. Compartimento impermeable y bolsillos ventilados para proteger tu equipamiento técnico.',
    short_desc: 'Diseño elegante impermeable para transportar tus patines con comodidad.',
    images: [
      { id: 'img_b1', product_id: 'b1', url: 'https://i.ibb.co/8gcN7Lc1/Bolso-Edea-always-with-me.png', sort_order: 0, is_primary: true }
    ],
    is_featured: true,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10,
    low_stock_threshold: 2,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    badge: 'Popular',
    badgeType: 'bestseller',
  },
  {
    id: 'b2',
    name: 'Bolso Portapatines Magic Rosa',
    slug: 'bolso-magic-rosa',
    brand_name: 'Edea',
    component_type: 'accesorio',
    skate_level: ['iniciacion', 'intermedio'],
    price_ars: 45000,
    description: 'Bolso ultra liviano y resistente con bolsillos para herramientas y rodamientos.',
    short_desc: 'Bolso compacto y juvenil para tus entrenamientos diarios.',
    images: [
      { id: 'img_b2', product_id: 'b2', url: 'https://i.ibb.co/8gcN7Lc1/Bolso-Edea-always-with-me.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 15,
    low_stock_threshold: 3,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'b3',
    name: 'Bolso Portapatines Magic Celeste',
    slug: 'bolso-magic-celeste',
    brand_name: 'Edea',
    component_type: 'accesorio',
    skate_level: ['iniciacion', 'intermedio'],
    price_ars: 45000,
    description: 'Bolso ergonómico diseñado para la comodidad en el transporte diario.',
    short_desc: 'Espacioso y con ventilación lateral integrada.',
    images: [
      { id: 'img_b3', product_id: 'b3', url: 'https://i.ibb.co/8gcN7Lc1/Bolso-Edea-always-with-me.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 12,
    low_stock_threshold: 3,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p5',
    name: 'Roll-Line Giotto',
    slug: 'roll-line-giotto',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['alto_rendimiento'],
    price_ars: 155000,
    description: 'La plancha Giotto es la elección de los campeones mundiales de figuras. Su precisión milimétrica y su construcción en aleación de aluminio de grado aeronáutico la hacen insuperable.',
    short_desc: 'Precisión absoluta para la disciplina de figuras.',
    images: [
      { id: 'img5_1', product_id: 'p5', url: 'https://i.ibb.co/k51S22Kx/Roll-Line-ruedas-giotto.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 4,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['figuras'],
    specs: [
      { label: 'Estabilidad', value: 98 },
      { label: 'Agilidad', value: 70 },
      { label: 'Peso', value: 75 },
      { label: 'Respuesta', value: 95 },
      { label: 'Precisión', value: 100 },
    ],
  },
  {
    id: 'p5_2',
    name: 'Roll-Line Energy',
    slug: 'roll-line-energy',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['alto_rendimiento'],
    price_ars: 185000,
    description: 'La plancha de competición por excelencia. Agilidad extrema y respuesta instantánea.',
    short_desc: 'La elección de los profesionales para saltos y piruetas.',
    images: [
      { id: 'img52_1', product_id: 'p5_2', url: '/images/products/plate-energy.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 6,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre', 'saltos'],
    specs: [
      { label: 'Estabilidad', value: 85 },
      { label: 'Agilidad', value: 100 },
      { label: 'Peso', value: 95 },
      { label: 'Respuesta', value: 100 },
      { label: 'Precisión', value: 95 },
    ],
  },
  {
    id: 'pm1',
    name: 'Roll-Line Matrix',
    slug: 'roll-line-matrix',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['alto_rendimiento'],
    price_ars: 245000,
    description: 'La plancha de más alto nivel para patinadores profesionales. Estructura rebajada y geometría diferenciada.',
    short_desc: 'Estructura ultraliviana rebajada de máxima precisión.',
    images: [
      { id: 'img_pm1', product_id: 'pm1', url: 'https://i.ibb.co/JWZ7ZvF6/Roll-Line-Matrix.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 3,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre', 'saltos'],
    specs: [
      { label: 'Estabilidad', value: 95 },
      { label: 'Agilidad', value: 98 },
      { label: 'Liviandad', value: 100 },
      { label: 'Respuesta', value: 98 },
    ],
  },
  {
    id: 'pm2',
    name: 'Roll-Line Evo',
    slug: 'roll-line-evo',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['alto_rendimiento'],
    price_ars: 225000,
    description: 'Una evolución tecnológica en el mundo de las planchas profesionales, con suspensiones de click micrométrico.',
    short_desc: 'Ajuste micrométrico y diseño de vanguardia.',
    images: [
      { id: 'img_pm2', product_id: 'pm2', url: 'https://i.ibb.co/YTw3VGP8/Roll-Line-Evo.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 4,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre'],
    specs: [
      { label: 'Estabilidad', value: 90 },
      { label: 'Agilidad', value: 95 },
      { label: 'Ajuste', value: 100 },
    ],
  },
  {
    id: 'pm3',
    name: 'Roll-Line Variant M',
    slug: 'roll-line-variant-m',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['intermedio'],
    price_ars: 98000,
    description: 'La plancha Variant M está diseñada para patinadores en ascenso. Excelente rigidez estructural de aluminio.',
    short_desc: 'Durabilidad y respuesta ágil de nivel intermedio.',
    images: [
      { id: 'img_pm3', product_id: 'pm3', url: 'https://i.ibb.co/nq9g9Td7/Roll-Line-Saturno.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 8,
    low_stock_threshold: 2,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre'],
    specs: [
      { label: 'Estabilidad', value: 80 },
      { label: 'Agilidad', value: 75 },
      { label: 'Durabilidad', value: 95 },
    ],
  },
  {
    id: 'pm4',
    name: 'Roll-Line Mistral',
    slug: 'roll-line-mistral',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['avanzado'],
    price_ars: 135000,
    description: 'Plancha técnica de alta gama con tren de aluminio y suspensiones en elastómero de primera calidad.',
    short_desc: 'Chasis excelente para deportistas de alto nivel y saltos.',
    images: [
      { id: 'img_pm4', product_id: 'pm4', url: 'https://i.ibb.co/jvMxyczh/Roll-Line-ruedas-magnum.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 5,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre', 'saltos'],
    specs: [
      { label: 'Estabilidad', value: 85 },
      { label: 'Agilidad', value: 88 },
      { label: 'Control', value: 90 },
    ],
  },
  {
    id: 'pm5',
    name: 'Roll-Line Mariner Cup',
    slug: 'roll-line-mariner-cup',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['intermedio', 'avanzado'],
    price_ars: 110000,
    description: 'Perfectamente calibrada para figuras obligatorias y saltos intermedios. Excelente relación calidad/precio.',
    short_desc: 'Estabilidad superior y diseño clásico comprobado.',
    images: [
      { id: 'img_pm5', product_id: 'pm5', url: 'https://i.ibb.co/7NSXMRkk/Roll-Line-ruedas-boxer.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 6,
    low_stock_threshold: 2,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['figuras'],
    specs: [
      { label: 'Estabilidad', value: 90 },
      { label: 'Control', value: 85 },
      { label: 'Precisión', value: 80 },
    ],
  },
  {
    id: 'pm6',
    name: 'Roll-Line Saturno',
    slug: 'roll-line-saturno',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['iniciacion'],
    price_ars: 72000,
    description: 'El chasis de iniciación ideal para academias y escuelas. Ligero, duradero y de fácil mantenimiento.',
    short_desc: 'Ligereza y confort para tus primeros giros.',
    images: [
      { id: 'img_pm6', product_id: 'pm6', url: 'https://i.ibb.co/vCcLCJzm/Roll-Line-Mistral-2.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 12,
    low_stock_threshold: 3,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre'],
    specs: [
      { label: 'Flexibilidad', value: 90 },
      { label: 'Estabilidad', value: 85 },
      { label: 'Peso', value: 80 },
    ],
  },
  {
    id: 'pm7',
    name: 'Roll-Line Giotto Titanium',
    slug: 'roll-line-giotto-titanium',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['alto_rendimiento'],
    price_ars: 215000,
    description: 'Plancha ultra-especializada de figuras obligatorias con ejes de titanio para una ligereza inalcanzable.',
    short_desc: 'Edición limitada en titanio para la máxima precisión técnica.',
    images: [
      { id: 'img_pm7', product_id: 'pm7', url: 'https://i.ibb.co/LdKwnRPZ/Roll-Line-Mirage.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 3,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['figuras'],
    specs: [
      { label: 'Precisión', value: 100 },
      { label: 'Liviandad', value: 98 },
      { label: 'Control', value: 98 },
    ],
  },
  {
    id: 'pm8',
    name: 'Roll-Line Energy Steel',
    slug: 'roll-line-energy-steel',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['alto_rendimiento'],
    price_ars: 178000,
    description: 'La plancha más vendida para saltos triples y cuádruples, equipada con ejes de acero reforzado.',
    short_desc: 'Máxima durabilidad para los saltos más extremos.',
    images: [
      { id: 'img_pm8', product_id: 'pm8', url: '/images/products/plancha-magic8.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 5,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre', 'saltos'],
    specs: [
      { label: 'Resistencia', value: 100 },
      { label: 'Agilidad', value: 90 },
      { label: 'Control', value: 95 },
    ],
  },
  {
    id: 'pm9',
    name: 'Roll-Line Energy Titanium',
    slug: 'roll-line-energy-titanium',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['alto_rendimiento'],
    price_ars: 235000,
    description: 'La joya de la corona. Plancha Energy con ejes de titanio para saltar más alto y girar más rápido.',
    short_desc: 'La plancha definitiva de competición para saltos y piruetas.',
    images: [
      { id: 'img_pm9', product_id: 'pm9', url: '/images/products/plancha-magic9.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 2,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['libre', 'saltos'],
    specs: [
      { label: 'Liviandad', value: 100 },
      { label: 'Agilidad', value: 100 },
      { label: 'Amortiguación', value: 98 },
    ],
  },
  {
    id: 'pm10',
    name: 'Roll-Line Dance',
    slug: 'roll-line-dance',
    brand_name: 'Roll-Line',
    component_type: 'plancha',
    skate_level: ['avanzado', 'alto_rendimiento'],
    price_ars: 165000,
    description: 'Geometría rebajada y trenes de ruedas optimizados para los movimientos fluidos y giros de solo danza.',
    short_desc: 'Diseñada específicamente para danza y precisión rítmica.',
    images: [
      { id: 'img_pm10', product_id: 'pm10', url: '/images/products/plancha-magic10.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 4,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skate_discipline: ['danza'],
    specs: [
      { label: 'Agilidad', value: 98 },
      { label: 'Flexibilidad', value: 95 },
      { label: 'Control', value: 95 },
    ],
  },
  {
    id: 'p6',
    name: 'Ruedas Roll-Line Giotto',
    slug: 'roll-line-ruedas-giotto',
    brand_name: 'Roll-Line',
    component_type: 'rueda',
    skate_level: ['avanzado'],
    price_ars: 45000,
    description: 'Ruedas profesionales con excelente agarre, ideales para patinaje libre.',
    short_desc: 'Set de 8 ruedas profesionales.',
    images: [
      { id: 'img6_1', product_id: 'p6', url: 'https://i.ibb.co/k51S22Kx/Roll-Line-ruedas-giotto.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 20,
    low_stock_threshold: 4,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    badge: 'Nuevo',
    badgeType: 'new',
    skate_discipline: ['libre', 'danza'],
    floorType: 'liso',
    specs: [
      { label: 'Agarre', value: 85 },
      { label: 'Velocidad', value: 90 },
      { label: 'Deslize', value: 75 },
      { label: 'Durabilidad', value: 80 },
      { label: 'Rebote', value: 88 },
    ],
  },
  {
    id: 'p6_2',
    name: 'Ruedas Roll-Line Magnum',
    slug: 'roll-line-ruedas-magnum',
    brand_name: 'Roll-Line',
    component_type: 'rueda',
    skate_level: ['intermedio'],
    price_ars: 40000,
    description: 'Perfectas para superficies rugosas y asfalto.',
    short_desc: 'Set de 8 ruedas para piso rugoso.',
    images: [
      { id: 'img62_1', product_id: 'p6_2', url: 'https://i.ibb.co/jvMxyczh/Roll-Line-ruedas-magnum.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 12,
    low_stock_threshold: 4,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    floorType: 'rugoso',
    skate_discipline: ['libre'],
    specs: [
      { label: 'Agarre', value: 95 },
      { label: 'Velocidad', value: 70 },
      { label: 'Deslize', value: 60 },
      { label: 'Durabilidad', value: 100 },
      { label: 'Amortiguación', value: 90 },
    ],
  },
  {
    id: 'p6_3',
    name: 'Ruedas Roll-Line Helium',
    slug: 'roll-line-ruedas-helium',
    brand_name: 'Roll-Line',
    component_type: 'rueda',
    skate_level: ['avanzado'],
    price_ars: 42000,
    description: 'Equilibrio perfecto para asfalto y superficies exteriores.',
    short_desc: 'Set de 8 ruedas mixtas.',
    images: [
      { id: 'img63_1', product_id: 'p6_3', url: 'https://i.ibb.co/SDTQ8ZBB/Roll-Line-ruedas-helium.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 15,
    low_stock_threshold: 4,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    floorType: 'mixto',
    skate_discipline: ['libre'],
    specs: [
      { label: 'Agarre', value: 90 },
      { label: 'Velocidad', value: 85 },
      { label: 'Deslize', value: 80 },
      { label: 'Durabilidad', value: 85 },
      { label: 'Amortiguación', value: 95 },
    ],
  },
  {
    id: 'p6_4',
    name: 'Ruedas Roll-Line Boxer',
    slug: 'roll-line-ruedas-boxer',
    brand_name: 'Roll-Line',
    component_type: 'rueda',
    skate_level: ['iniciacion'],
    price_ars: 35000,
    description: 'Ruedas ideales para quienes comienzan en el patinaje artístico.',
    short_desc: 'Set de 8 ruedas de iniciación.',
    images: [
      { id: 'img64_1', product_id: 'p6_4', url: 'https://i.ibb.co/7NSXMRkk/Roll-Line-ruedas-boxer.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 30,
    low_stock_threshold: 5,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    floorType: 'liso',
    skate_discipline: ['libre', 'danza'],
    specs: [
      { label: 'Agarre', value: 80 },
      { label: 'Velocidad', value: 85 },
      { label: 'Deslize', value: 80 },
      { label: 'Durabilidad', value: 85 },
      { label: 'Versatilidad', value: 100 },
    ],
  },
  {
    id: 'p4',
    name: 'Combo Iniciación Profesional',
    slug: 'combo-iniciacion',
    brand_name: 'Sobre Ruedas',
    component_type: 'combo',
    skate_level: ['iniciacion'],
    price_ars: 135000,
    compare_price: 165000,
    description: 'Todo lo que necesitas para empezar con el pie derecho. Incluye bota de cuero reforzado, plancha de aluminio liviano y ruedas de dureza media aptas para todo tipo de superficies.',
    short_desc: 'Set completo: Bota + Plancha + Ruedas + Rodamientos.',
    images: [
      { id: 'img4_1', product_id: 'p4', url: '/images/products/risport-antares.png', sort_order: 0, is_primary: true }
    ],
    is_featured: false,
    is_active: true,
    is_outlet: false,
    stock_quantity: 10,
    low_stock_threshold: 2,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    badge: '20% OFF',
    badgeType: 'discount',
    skate_discipline: ['libre'],
  },
  {
    id: 'ice_1',
    name: 'Cuchilla John Wilson Pattern 99',
    slug: 'cuchilla-john-wilson-pattern-99',
    brand_name: 'John Wilson',
    component_type: 'cuchilla',
    skate_level: ['alto_rendimiento'],
    skate_type: 'hielo',
    price_ars: 550000,
    description: 'La cuchilla elegida por los campeones mundiales. Acero al carbono de la más alta calidad.',
    short_desc: 'Cuchilla de nivel elite para saltos triples y cuádruples.',
    images: [{ id: 'img_ice_1', product_id: 'ice_1', url: '', sort_order: 0, is_primary: true }], // placeholder
    is_active: true,
    is_featured: true,
    is_outlet: false,
    stock_quantity: 5,
    low_stock_threshold: 2,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'ice_2',
    name: 'Cuchilla MK Professional',
    slug: 'cuchilla-mk-professional',
    brand_name: 'MK',
    component_type: 'cuchilla',
    skate_level: ['intermedio', 'avanzado'],
    skate_type: 'hielo',
    price_ars: 280000,
    description: 'La cuchilla más popular para patinadores en desarrollo. Excelente balance y control.',
    short_desc: 'Cuchilla ideal para saltos simples y dobles.',
    images: [{ id: 'img_ice_2', product_id: 'ice_2', url: '', sort_order: 0, is_primary: true }], // placeholder
    is_active: true,
    is_featured: false,
    is_outlet: false,
    stock_quantity: 8,
    low_stock_threshold: 3,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'ice_3',
    name: 'Cuchilla Jackson Ultima Matrix',
    slug: 'cuchilla-jackson-ultima-matrix',
    brand_name: 'Jackson',
    component_type: 'cuchilla',
    skate_level: ['avanzado', 'alto_rendimiento'],
    skate_type: 'hielo',
    price_ars: 420000,
    description: 'Chasis de aluminio ligero con filo de acero inoxidable. 33% más liviana que las cuchillas tradicionales.',
    short_desc: 'Cuchilla ultraligera de rendimiento avanzado.',
    images: [{ id: 'img_ice_3', product_id: 'ice_3', url: '', sort_order: 0, is_primary: true }], // placeholder
    is_active: true,
    is_featured: false,
    is_outlet: false,
    stock_quantity: 4,
    low_stock_threshold: 1,
    track_inventory: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
];

export const BRANDS = ['Edea', 'Risport', 'Roll-Line', 'Komplex', 'Jackson', 'Sobre Ruedas', 'Sobre Ruedas Academy'];
export const CATEGORIES = [
  { id: 'bota', label: 'Botas' },
  { id: 'plancha', label: 'Planchas' },
  { id: 'rueda', label: 'Ruedas' },
  { id: 'accesorio', label: 'Bolsos y Accesorios' },
  { id: 'combo', label: 'Combos' },
  { id: 'curso', label: 'Cursos' },
  { id: 'cuchilla', label: 'Cuchillas' },
];
export const LEVELS = [
  { id: 'iniciacion', label: 'Iniciación' },
  { id: 'intermedio', label: 'Intermedio' },
  { id: 'avanzado', label: 'Avanzado' },
  { id: 'alto_rendimiento', label: 'Alto Rendimiento' },
];
